# Generated by Django 4.2.2 on 2023-06-21 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctorsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_img', models.ImageField(upload_to='doctors')),
                ('doc_name', models.CharField(max_length=25)),
                ('doc_spec', models.CharField(max_length=200)),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospitalapp.departmentmodel')),
            ],
        ),
    ]
