# Generated by Django 4.2.2 on 2023-06-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0002_doctorsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorsmodel',
            name='doc_img',
            field=models.ImageField(upload_to='Hospitalapp/static'),
        ),
    ]
