# Generated by Django 4.2.2 on 2023-06-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0004_bookingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='booking_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
