# Generated by Django 4.2.2 on 2023-06-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0007_alter_bookingmodel_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='doc_name',
            field=models.CharField(max_length=25),
        ),
    ]
