# Generated by Django 4.2.2 on 2023-06-27 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0008_alter_bookingmodel_doc_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='doc_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospitalapp.doctorsmodel'),
        ),
    ]
